### ISSUE TITLE
Fast fontbredd i X-fönstret vore trevligt!

### ISSUE THREAD

**Issue by ChristerNilsson** [ChristerNilsson/2023#6]
Standard bland utvecklare

**Comment by BertilF** [comment]
Så här kanske?
Men det kommer att få plats färre bokstäver på en rad.
![FastFontbredd-courier new](https://github.com/ChristerNilsson/2023/assets/74978899/97a0eabd-a69a-485d-be3f-3ecd6a894f74)

**Comment by ChristerNilsson** [comment]
Ser utmärkt ut.
Man får leva med lite färre tecken per rad.
